# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_L9lnFkD_vJXzJzyDUVyelnApl7PkChs
"""

import json
import os

kaggle_json = {
    "username": "token",
    "key": "PASTE_YOUR_TOKEN_HERE"
}

os.makedirs("/root/.config/kaggle", exist_ok=True)

with open("/root/.config/kaggle/kaggle.json", "w") as f:
    json.dump(kaggle_json, f)

!chmod 600 /root/.config/kaggle/kaggle.json

!kaggle datasets list

!kaggle datasets download -d rtatman/blog-authorship-corpus
!unzip blog-authorship-corpus.zip

file_path = "blogtext.csv"

#imports
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import LinearSVC
from sklearn.metrics import accuracy_score, classification_report

from sklearn.metrics.pairwise import cosine_similarity
import joblib

file_path = "blogtext.csv"

df_human = pd.read_csv(
    file_path,
    usecols=["id", "text"],
    encoding="latin-1",
    engine="python",
    on_bad_lines="skip"
)

df_human.rename(columns={"id": "author"}, inplace=True)

print("Loaded shape:", df_human.shape)
df_human.head()

author_counts = df_human["author"].value_counts()

print("Total unique authors:", author_counts.shape[0])
author_counts.head(10)

#for ai authors
!kaggle datasets download -d sunilthite/llm-detect-ai-generated-text-dataset
!unzip llm-detect-ai-generated-text-dataset.zip

df_ai_raw = pd.read_csv(
    "Training_Essay_Data.csv",        # replace with actual csv name
    usecols=["text", "generated"]
)

df_ai_raw.head()

#Preparing Human Authors (40 authors)

HUMAN_AUTHORS = 40
SAMPLES_PER_AUTHOR = 300

author_counts = df_human["author"].value_counts()
selected_humans = author_counts[author_counts >= SAMPLES_PER_AUTHOR].index[:HUMAN_AUTHORS]

df_human = df_human[df_human["author"].isin(selected_humans)]

df_human = (
    df_human.groupby("author", group_keys=False)
            .apply(lambda x: x.sample(SAMPLES_PER_AUTHOR, random_state=42))
)

df_human["author_type"] = "human"

print(df_human.shape)

#Preparing AI authors (10)

AI_AUTHORS = 10
AI_SAMPLES_PER_AUTHOR = 300

ai_only = df_ai_raw[df_ai_raw["generated"] == 1].reset_index(drop=True)

ai_rows = []

for i in range(AI_AUTHORS):
    subset = ai_only.iloc[i*AI_SAMPLES_PER_AUTHOR:(i+1)*AI_SAMPLES_PER_AUTHOR]
    for t in subset["text"]:
        ai_rows.append({
            "author": f"AI_AUTHOR_{i}",
            "text": t,
            "author_type": "ai"
        })

df_ai = pd.DataFrame(ai_rows)

print(df_ai.shape)

#Combining both ai and human datasets

df = pd.concat([df_human, df_ai], ignore_index=True)

print(df["author"].nunique(), "total authors")

# Encode Labels


# 🔑 Force all author labels to be strings
df["author"] = df["author"].astype(str)

label_encoder = LabelEncoder()
df["label"] = label_encoder.fit_transform(df["author"])

X = df["text"]
y = df["label"]

print("Total classes:", len(label_encoder.classes_))

# Train/Test Split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,
    random_state=42
)

#  Feature Extraction

from scipy.sparse import hstack

# Character n-grams (style)
char_vectorizer = TfidfVectorizer(
    analyzer="char",
    ngram_range=(3,5),
    max_features=40000,
    min_df=5
)

# Word n-grams (phrasing)
word_vectorizer = TfidfVectorizer(
    analyzer="word",
    ngram_range=(1,2),
    max_features=20000,
    min_df=5
)

X_train_char = char_vectorizer.fit_transform(X_train)
X_test_char  = char_vectorizer.transform(X_test)

X_train_word = word_vectorizer.fit_transform(X_train)
X_test_word  = word_vectorizer.transform(X_test)

# Combine both
X_train_vec = hstack([X_train_char, X_train_word])
X_test_vec  = hstack([X_test_char, X_test_word])

print("Final feature space:", X_train_vec.shape)

# Train Classifier

clf = LinearSVC(
    C=1.0,
    class_weight="balanced"
)

clf.fit(X_train_vec, y_train)

# Evaluation

y_pred = clf.predict(X_test_vec)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

def top_k_accuracy(clf, X, y_true, k=5):
    scores = clf.decision_function(X)
    top_k_preds = np.argsort(scores, axis=1)[:, -k:]
    correct = sum(y_true[i] in top_k_preds[i] for i in range(len(y_true)))
    return correct / len(y_true)

for k in [1, 3, 5]:
    acc = top_k_accuracy(clf, X_test_vec, y_test.values, k)
    print(f"Top-{k} Accuracy: {acc:.3f}")

# Saving Model Report

import joblib

joblib.dump(clf, "author_classifier.pkl")
joblib.dump(char_vectorizer, "char_vectorizer.pkl")
joblib.dump(word_vectorizer, "word_vectorizer.pkl")
joblib.dump(label_encoder, "label_encoder.pkl")

print("Model and vectorizers saved successfully.")

# Load trained components
clf = joblib.load("author_classifier.pkl")
char_vectorizer = joblib.load("char_vectorizer.pkl")
word_vectorizer = joblib.load("word_vectorizer.pkl")
label_encoder = joblib.load("label_encoder.pkl")

print("Inference components loaded.")

def vectorize_text(text):
    X_char = char_vectorizer.transform([text])
    X_word = word_vectorizer.transform([text])
    return hstack([X_char, X_word])

# Author Identification Function

CONFIDENCE_THRESHOLD = 0.25

def predict_author(text):
    vec = vectorize_text(text)
    scores = clf.decision_function(vec)

    best_score = np.max(scores)
    best_label = np.argmax(scores)

    if best_score < CONFIDENCE_THRESHOLD:
        return {"prediction": "UNKNOWN_AUTHOR", "confidence": float(best_score)}

    author = label_encoder.inverse_transform([best_label])[0]
    return {"prediction": author, "confidence": float(best_score)}

#  Register New Author

registered_author_vectors = {}

def register_author(author_name, text):
    vec = vectorize_text(text)
    registered_author_vectors[author_name] = vec
    print(f"Registered author: {author_name}")

# Identify Returning Author

def identify_registered_author(text, threshold=0.6):
    vec = vectorize_text(text)

    best_match = None
    best_score = 0

    for author, stored_vec in registered_author_vectors.items():
        score = cosine_similarity(vec, stored_vec)[0][0]
        if score > best_score:
            best_score = score
            best_match = author

    if best_score >= threshold:
        return {"prediction": best_match, "similarity": float(best_score)}

    return {"prediction": "UNKNOWN_AUTHOR", "similarity": float(best_score)}

